### ISSUE TITLE
CHEAP VPS HOST

### ISSUE THREAD

**Issue by jollesnaas** [OgarPlus/Ogar-Plus#15]

**Comment by Andrews54757** [comment]
i dont trust this . dont fall for it others! Only give money to trusted people

**Comment by jollesnaas** [comment]
@Andrews54757 Why?

**Comment by Andrews54757** [comment]
its obvious. You are holding all the cards. You can shut down the server any time, You can make people pay more than they want to. And you never specified the cpu. Also, OVH is cheaper and is relieable
