### ISSUE TITLE
Sad to see this project dead.

### ISSUE THREAD

**Issue by Agarian** [OgarPlus/Ogar-Plus#18]
It really could have become something.

**Comment by DaFudgeWizzad** [comment]
It was fun while it lasted.

**Comment by Agarian** [comment]
Hmm... what if it doesn't have to be? I have some friends back at github.com/Megabyte918/MultiOgar-Edited that just may be able to help.

**Comment by DaFudgeWizzad** [comment]
Anyone is allowed to use parts of OgarPlus for their own projects, but I am working on bigger projects myself. I would be happy to help solve any issues that come by, if you or anyone else runs into any.
