### ISSUE TITLE
how countdown FFA?

### ISSUE THREAD

**Issue by mafiakb** [OgarPlus/Ogar-Plus#2]
FFA with time limit is possible?

**Comment by Porama6400** [comment]
sorry for the late reply

do you mean kill everyone and start all over after 10 minutes or something like that?
yes , it's possible


sorry for my bad english skills

**Comment by Porama6400** [comment]
how often do you want to reset?

**Comment by mafiakb** [comment]
Yes kill everyone and start in reset time 1 hour but in FFA.

**Comment by DaFudgeWizzad** [comment]
Working on it!

**Comment by Porama6400** [comment]
Default will be set to once per hour
is it okay?

**Comment by mafiakb** [comment]
Yes, i test now

**Comment by mafiakb** [comment]
You can add this?
```
case 1:
            lb[0] = "Game starting in";
            lb[1] = this.timer.toString();
            lb[2] = "Good luck!";
            if (this.timer <= 0) {
                // Reset the game
                this.startGame(gameServer);
            } else {
                this.timer--;
            }
            break;
        case 2:
            lb[0] = "Players Remaining";
            lb[1] = this.contenders.length+"/"+this.maxContenders;
            lb[2] = "Time Limit:";
            lb[3] = this.formatTime(this.timeLimit);
            if (this.timeLimit < 0) {
                // Timed out
                this.endGameTimeout(gameServer);
            } else {
                this.timeLimit--;
            }
            break;
        case 3:
            lb[0] = "Congratulations";
            lb[1] = this.winner.getName();
            lb[2] = "for winning!";
            if (this.timer <= 0) {
                // Reset the game
                this.onServerInit(gameServer);
                // Respawn starting food
                gameServer.startingFood();
            } else {
                lb[3] = "Game restarting in";
                lb[4] = this.timer.toString();
                this.timer--;
            }
            break;
        case 4:
            lb[0] = "Time Limit"; 
            lb[1] = "Reached!";
            if (this.timer <= 0) {
                // Reset the game
                this.onServerInit(gameServer);
                // Respawn starting food
                gameServer.startingFood();
            } else {
                lb[2] = "Game restarting in";
                lb[3] = this.timer.toString();
                this.timer--;
            }
```

**Comment by mafiakb** [comment]
hi?

**Comment by Porama6400** [comment]
sorry for late response (again?)
where should your code put in? (Where is it design for)

you can also write it and send pull request
# sorry for my bad English skills

**Comment by Porama6400** [comment]
#### Do you copy it from another Agar.io Private Server?
i need to rewrite if you copy it

**Comment by mafiakb** [comment]
This is my url agar.io http://agar.io/?ip=207.244.68.67:443
i use u new game ffatime but  need Time Limit how tournament

**Comment by Porama6400** [comment]
where is your code come from?
do you make it yourself?

**Comment by Porama6400** [comment]
and where should i put it in?

**Comment by mafiakb** [comment]
This is my ogar http://i.imgur.com/xlMl6yC.png

this is one example http://i.imgur.com/pRUTLHr.png

**Comment by mafiakb** [comment]
this is one example http://i.imgur.com/9kLdvQ1.png with time limit

**Comment by mafiakb** [comment]
hi?

**Comment by DaFudgeWizzad** [comment]
Sorry for the difficulties, would you please add in note to your code explaining it does? EX:
// Remove ejected mass
gameServer.removeNode(e);

**Comment by Porama6400** [comment]
soon

**Comment by mafiakb** [comment]
Hi, you speak for this code?

        case 1:
            lb[0] = "Game starting in";
            lb[1] = this.timer.toString();
            lb[2] = "Good luck!";
            if (this.timer <= 0) {
                // Reset the game
                this.startGame(gameServer);
            } else {
                this.timer--;
            }
            break;

Is of tournament code for add "FFATime", I attach one image, how example.

**Comment by mafiakb** [comment]
hi?

**Comment by mafiakb** [comment]
:(

**Comment by DaFudgeWizzad** [comment]
Just made a really advanced version that includes this. :) have fun

**Comment by mafiakb** [comment]
Thank you, but missing names leaderboard

**Comment by DaFudgeWizzad** [comment]
Working on finding a solution since only text or usernames are allowed

**Comment by DaFudgeWizzad** [comment]
I have found that without professional dedication, this isn't very possible. We either have text or the 10 player leaderboard.
