### ISSUE TITLE
Experimental mothercell problem

### ISSUE THREAD

**Issue by Porama6400** [OgarPlus/Ogar-Plus#5]
as inohtech issue at https://github.com/OgarPlus/Ogar-Plus-GUI/issues/1

it's because eating mothercell that not remove properly after change gamemode from Experimental to other gamemode

Ogar-Plus ~ A modified Ogar Server
[Ogar-Plus] Loaded stats server on port 88
[Ogar-Plus] Listening on port 666
[Ogar-Plus] Current game mode is Experimental
[Ogar-Plus] Remote GUI Authecation Key : ####

[Ogar-Plus] Remote GUI connected!
[Ogar-Plus] Remote GUI address : ###.###.#.###:56676
[Ogar-Plus] Removed 1 cells
[Ogar-Plus] Successfully changed leaderboard values
[Ogar-Plus] Added 3 player bots
[Ogar-Plus] Added 1 player bots
[Ogar-Plus] Changed game mode to Virus Off
[Ogar-Plus] Changed game mode to AirDrop
[Ogar-Plus] Changed game mode to AirDrop
[Ogar-Plus] Changed game mode to Zombie FFA
[Ogar-Plus] Changed game mode to Zombie Team
TypeError: Cannot read property 'indexOf' of undefined
at Cell.Math.Enclose.+c+:++t+h+e+b+o+x++U+s+e+r+s++F+u+j+i+t+s+u++D+o+c+
u+m+e+n+t+s++G+i+t+H+u+b++O+g+a+r+-+P+l+u+s++s+r+c++g+a+m+e+m+o+d+e+s++E+x+
p+e+r+i+m+e+n+t+a+l+.+j+s.MotherCell.onRemove ()
at GameServer.Math.Enclose.+c+:++t+h+e+b+o+x++U+s+e+r+s++F+u+j+i+t+s+u++
D+o+c+u+m+e+n+t+s++G+i+t+H+u+b++O+g+a+r+-+P+l+u+s++s+r+c++G+a+m+e+S+e+r+v+e+
r+.+j+s.GameServer.removeNode ()
at GameServer.Math.Enclose.+c+:++t+h+e+b+o+x++U+s+e+r+s++F+u+j+i+t+s+u++
D+o+c+u+m+e+n+t+s++G+i+t+H+u+b++O+g+a+r+-+P+l+u+s++s+r+c++G+a+m+e+S+e+r+v+e+
r+.+j+s.GameServer.updateMoveEngine ()
at GameServer.Math.Enclose.+c+:++t+h+e+b+o+x++U+s+e+r+s++F+u+j+i+t+s+u++
D+o+c+u+m+e+n+t+s++G+i+t+H+u+b++O+g+a+r+-+P+l+u+s++s+r+c++G+a+m+e+S+e+r+v+e+
r+.+j+s.GameServer.cellTick ()
at GameServer.Math.Enclose.+c+:++t+h+e+b+o+x++U+s+e+r+s++F+u+j+i+t+s+u++
D+o+c+u+m+e+n+t+s++G+i+t+H+u+b++O+g+a+r+-+P+l+u+s++s+r+c++G+a+m+e+S+e+r+v+e+
r+.+j+s.GameServer.mainLoop ()
at wrapper as _onTimeout
at Timer.listOnTimeout (timers.js:119:15)

**Comment by DaFudgeWizzad** [comment]
This is an Ogar bug. The gamemode command isn't very stable

**Comment by Porama6400** [comment]
we have to properly remove mothercell

**Comment by DaFudgeWizzad** [comment]
I don't know how to do that, especially since it involves removing nodes
