### ISSUE TITLE
Spawning directly in-front of people and eating them.

### ISSUE THREAD

**Issue by NatsuTheGreat** [OgarPlus/Ogar-Plus#8]
Okay so I have this bug where people randomly spawn on you and eat you whole. This is non stop, you don't spawn at an empty place, you always and only spawn on a player or inside them.. And this is getting annoying, any ideas on how to fix this?

(this is my private server) I am using ogar-plus

**Comment by DaFudgeWizzad** [comment]
I will be able to fix this later this weekend.

**Comment by NatsuTheGreat** [comment]
Okay. I have we can fix it because I get a lot of complaints xP. I have the rest of today and then tomorrow, and it's school time.

Wish you good luck on fixing this! :D

**Comment by NatsuTheGreat** [comment]
is it fixed?

**Comment by Porama6400** [comment]
Are you still have that problem?

**Comment by NatsuTheGreat** [comment]
It's been years, I fixed it already xP

**Comment by NatsuTheGreat** [comment]
I will close this xP
